services:
  - type: web
    name: whisper-transcriptor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: TU_API_KEY
